version: '3'

services:
  app:
    build: .
    volumes:
      - ./:/app
    ports:
      - "4000:4000"
    working_dir: /app
    command: uvicorn main:app --app-dir ./app  --reload --host 0.0.0.0 --port 4000
